$SQL= "
SELECT DISTINCT
      ARTICLES.ART_ID AS PID
    , BRANDS.BRA_MFC_CODE AS BKEY
    , ARTICLES.ART_ARTICLE_NR AS AKEY
	, BRANDS.BRA_BRAND AS BRAND
	, ART_LOOKUP.ARL_SEARCH_NUMBER AS ARTICLE
	, ".$CurrCategory." AS CATEGORY
FROM ARTICLES 

INNER JOIN BRANDS
    ON ARTICLES.ART_SUP_ID = BRANDS.BRA_ID

INNER JOIN ART_LOOKUP
    ON (
			ARTICLES.ART_ID = ART_LOOKUP.ARL_ART_ID 
		AND	ART_LOOKUP.ARL_KIND = 1
		AND	ART_LOOKUP.ARL_BRA_ID=0
	)

WHERE EXISTS(
    SELECT * 
    FROM LINK_ART 
    INNER JOIN LINK_GA_STR 
        ON LINK_GA_STR.LGS_STR_ID	 = ".$CurrCategory."
       AND LINK_ART.LA_GA_ID		 = LINK_GA_STR.LGS_GA_ID
    WHERE ARTICLES.ART_ID = LINK_ART.LA_ART_ID
)
ORDER BY ARTICLES.ART_ARTICLE_NR
LIMIT 0, 30
";