<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace app\assets;

use function var_export;
use yii\web\AssetBundle;

/**
 * Main application asset bundle.
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
 
 
class AppAsset extends AssetBundle
{
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
        'yii\bootstrap\BootstrapPluginAsset',
    ];
    public $basePath = '@webroot';
    public $baseUrl = '@web';
	public $css = [
                'css/site.css',
				'css/jquery.inputfile.css',
                'css/style.css',
			];
    public $js = [
        'js/jquery.inputfile.js',
        'js/common.js'
    ];
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (\Yii::$app->language=='ar'){
            $this->css[]='css/arab.css';
        }
    }

}
